# NOTE(artom) We need to install cruini and iniparse from source until
# https://github.com/pixelb/crudini/issues/58 and
# https://github.com/candlepin/python-iniparse/issues/5 are on fixed PyPi.
- name: crudini and iniparse
  pip:
      name: "{{ item }}"
      state: present
  with_items:
      - git+https://github.com/pixelb/crudini.git#egg=crudini
      - git+https://github.com/candlepin/python-iniparse.git#egg=iniparse
  become: yes

# NOTE(artom) The run-tempest role runs as the tempest user, so we need to give
# the tempest user SSH access to all hosts. Devstack's orchestrate-devstack
# role should have put a pubkey into the stack user's authorized_keys, so if we
# put the corresponding private key in the tempest user's .ssh, things should
# magically work.
- name: Setup tempest SSH key
  include_role:
      name: copy-build-sshkey
  vars:
      copy_sshkey_target_user: 'tempest'
  become: yes
