# TODO(artom) Once https://review.opendev.org/#/c/679656/ merges, we can unify
# the nodeset names and use the one in Nova. Until then, have a different name
# here.
- nodeset:
    name: multi-numa-multinode
    nodes:
      - name: controller
        label: multi-numa-ubuntu-bionic
      - name: compute
        label: multi-numa-ubuntu-bionic
    groups:
      # Node where tests are executed and test results collected
      - name: tempest
        nodes:
          - controller
      # Nodes running the compute service
      - name: compute
        nodes:
          - controller
          - compute
      # Nodes that are not the controller
      - name: subnode
        nodes:
          - compute
      # Switch node for multinode networking setup
      - name: switch
        nodes:
          - controller
      # Peer nodes for multinode networking setup
      - name: peers
        nodes:
          - compute

- job:
    name: whitebox-multinode-devstack
    nodeset: multi-numa-multinode
    parent: tempest-multinode-full-py3
    description: |
        Devstack multinode job.
    required-projects:
        x/whitebox-tempest-plugin
    pre-run: playbooks/whitebox.yaml
    irrelevant-files:
      - ^test-requirements.txt$
    vars:
        tox_envlist: all
        tempest_concurrency: 1
        tempest_test_regex: ^whitebox_tempest_plugin\.
        devstack_plugins:
            whitebox-tempest-plugin: https://opendev.org/x/whitebox-tempest-plugin.git
        devstack_localrc:
            MAX_COMPUTE_NODES: 2
            LIBVIRT_TYPE: kvm
            TEMPEST_PLUGINS: /opt/stack/whitebox-tempest-plugin
            WHITEBOX_PRIVKEY_PATH: /home/tempest/.ssh/id_rsa
    group-vars:
        subnode:
            num_hugepages: 2048
            devstack_localrc:
                LIBVIRT_TYPE: kvm
        tempest:
            num_hugepages: 512

- project:
    name: x/whitebox-tempest-plugin
    templates:
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
    check:
        jobs:
            - whitebox-multinode-devstack
    gate:
        jobs:
            - whitebox-multinode-devstack
