- nodeset:
    name: nested-virt-multinode
    nodes:
      - name: controller
        label: nested-virt-ubuntu-focal
      - name: compute
        label: nested-virt-ubuntu-focal
    groups:
      # Node where tests are executed and test results collected
      - name: tempest
        nodes:
          - controller
      # Nodes running the compute service
      - name: compute
        nodes:
          - controller
          - compute
      # Nodes that are not the controller
      - name: subnode
        nodes:
          - compute
      # Switch node for multinode networking setup
      - name: switch
        nodes:
          - controller
      # Peer nodes for multinode networking setup
      - name: peers
        nodes:
          - compute

- job:
    name: whitebox-devstack-multinode-base
    abstract: true
    parent: tempest-multinode-full-py3
    nodeset: nested-virt-multinode
    description: |
      Runs the entire test suite on single-NUMA, non-SMT, nested virt VMs.
    required-projects:
      openstack/whitebox-tempest-plugin
    pre-run: playbooks/whitebox/pre.yaml
    irrelevant-files:
      - ^test-requirements.txt$
    vars:
      tox_envlist: all
      tempest_concurrency: 1
      tempest_test_regex: ^whitebox_tempest_plugin\.
      devstack_plugins:
        whitebox-tempest-plugin: https://opendev.org/openstack/whitebox-tempest-plugin.git
      devstack_localrc:
        MAX_COMPUTE_NODES: 2
        LIBVIRT_TYPE: kvm
        TEMPEST_PLUGINS: /opt/stack/whitebox-tempest-plugin
        WHITEBOX_PRIVKEY_PATH: /home/tempest/.ssh/id_rsa
        WHITEBOX_CPU_MODEL: kvm64
        WHITEBOX_CPU_MODEL_EXTRA_FLAGS: vme,+ssse3,-mmx
        WHITEBOX_CPU_TOPOLOGY: "0: [0,1,2,3,4,5,6,7]"
      devstack_local_conf:
        post-config:
          $NOVA_CONF:
            libvirt:
              cpu_mode: custom
              cpu_models: kvm64
              cpu_model_extra_flags: vme,+ssse3,-mmx
              virt_type: kvm
              rx_queue_size: 1024
    group-vars:
      subnode:
        num_hugepages: 2048
        devstack_localrc:
          LIBVIRT_TYPE: kvm
        devstack_local_conf:
          post-config:
            $NOVA_CONF:
              libvirt:
                cpu_mode: custom
                cpu_models: kvm64
                cpu_model_extra_flags: vme,+ssse3,-mmx
                virt_type: kvm
                rx_queue_size: 1024
      tempest:
        num_hugepages: 512

- job:
    name: whitebox-devstack-multinode
    parent: whitebox-devstack-multinode-base
    vars:
      # NOTE(artom) We can't have this on the parent job, otherwise the two
      # -cpupinnig jobs will inherit it as well.
      tempest_exclude_regex: test_live_migrate_and_reboot

- job:
    name: whitebox-devstack-multinode-cpupinning
    parent: whitebox-devstack-multinode-base
    description: |
      Runs the CPU pinning tests on single-NUMA, non-SMT, nested virt VMs. Uses
      [compute]cpu_dedicated_set to configure host CPUs for pinning.
    vars:
      tempest_test_regex: 'test_live_migrate_and_reboot'
      devstack_local_conf:
        post-config:
          $NOVA_CONF:
            compute:
              cpu_dedicated_set: '0-3'
              cpu_shared_set: '4,5'
    group-vars:
      subnode:
        devstack_local_conf:
          post-config:
            $NOVA_CONF:
              compute:
                cpu_dedicated_set: '4-7'
                cpu_shared_set: '2,3'

- job:
    name: whitebox-devstack-multinode-cpupinninglegacy
    parent: whitebox-devstack-multinode-base
    description: |
      Runs the CPU pinning tests on single-NUMA, non-SMT, nested virt VMs. Uses
      [DEFAULT]vcpu_pin_set to configure host CPUs for pinning.
    vars:
      tempest_test_regex: 'test_live_migrate_and_reboot'
      devstack_local_conf:
        post-config:
          $NOVA_CONF:
            DEFAULT:
              vcpu_pin_set: '0-3'
            compute:
              cpu_shared_set: '4,5'
    group-vars:
      subnode:
        devstack_local_conf:
          post-config:
            $NOVA_CONF:
              DEFAULT:
                vcpu_pin_set: '4-7'
              compute:
                cpu_shared_set: '2,3'

- project:
    templates:
      - openstack-python3-xena-jobs
    check:
      jobs:
        - whitebox-devstack-multinode
        - whitebox-devstack-multinode-cpupinning
        - whitebox-devstack-multinode-cpupinninglegacy
    gate:
      jobs:
        - whitebox-devstack-multinode
        - whitebox-devstack-multinode-cpupinning
        - whitebox-devstack-multinode-cpupinninglegacy
